ln -s answerkey.m.1FQB answerkey.m
ln -s myinput.m.1FQB myinput.m
ln -s NOES.txt.1FQB NOES.txt
ln -s order.m.1FQB order.m
ln -s TOCSY.m.1FQB TOCSY.m
ln -s MySHIFTS.7.model6.1FQB SHIFTS/MySHIFTS.7.model6
ln -s MySHIFTX.7.model6.1FQB SHIFTX/MySHIFTX.7.model6
ln -s N-H_vectors.m.1FQB N-H_vectors.m
ln -s N-H_medium1.m.1FQB N-H_medium1.m
ln -s N-C_vectors.m.1FQB N-C_vectors.m
ln -s N-C_medium1.m.1FQB N-C_medium1.m
ln -s C-Ca_vectors.m.1FQB C-Ca_vectors.m
ln -s C-Ca_medium1.m.1FQB C-Ca_medium1.m
