ln -s answerkey.m.MBP answerkey.m
ln -s myinput.m.MBP myinput.m
ln -s NOES.txt.MBP NOES.txt
ln -s order.m.MBP order.m
ln -s TOCSY.m.MBP TOCSY.m
ln -s MySHIFTS.7.model6.MBP SHIFTS/MySHIFTS.7.model6
ln -s MySHIFTX.7.model6.MBP SHIFTX/MySHIFTX.7.model6
ln -s N-H_vectors.m.MBP N-H_vectors.m
ln -s N-H_medium1.m.MBP N-H_medium1.m
ln -s N-C_vectors.m.MBP N-C_vectors.m
ln -s N-C_medium1.m.MBP N-C_medium1.m
ln -s C-Ca_vectors.m.MBP C-Ca_vectors.m
ln -s C-Ca_medium1.m.MBP C-Ca_medium1.m
