ln -s answerkey.m.poln answerkey.m
ln -s myinput.m.poln myinput.m
ln -s NOES.txt.poln NOES.txt
ln -s order.m.poln order.m
ln -s TOCSY.m.poln TOCSY.m
ln -s MySHIFTS.7.model6.poln SHIFTS/MySHIFTS.7.model6
ln -s MySHIFTX.7.model6.poln SHIFTX/MySHIFTX.7.model6
ln -s C-H_vectors.m.poln C-H_vectors.m
ln -s C-H_medium.m.poln C-H_medium1.m
ln -s N-H_vectors.m.poln N-H_vectors.m
ln -s N-H_medium.m.poln N-H_medium1.m
