ln -s answerkey.m.gb1 answerkey.m
ln -s myinput.m.gb1 myinput.m
ln -s NOES.txt.gb1 NOES.txt
ln -s order.m.gb1 order.m
ln -s TOCSY.m.gb1 TOCSY.m
ln -s MySHIFTS.7.model6.gb1 SHIFTS/MySHIFTS.7.model6
ln -s MySHIFTX.7.model6.gb1 SHIFTX/MySHIFTX.7.model6
ln -s C-H_vectors.m.gb1 C-H_vectors.m
ln -s C-H_medium.m.gb1 C-H_medium1.m
ln -s N-H_vectors.m.gb1 N-H_vectors.m
ln -s N-H_medium.m.gb1 N-H_medium1.m
