ln -s answerkey.m.1G6J answerkey.m
ln -s myinput.m.1G6J myinput.m
ln -s NOES.txt.1G6J NOES.txt
ln -s order.m.1G6J order.m
ln -s TOCSY.m.1G6J TOCSY.m
ln -s MySHIFTS.7.model6.1G6J SHIFTS/MySHIFTS.7.model6
ln -s MySHIFTX.7.model6.1G6J SHIFTX/MySHIFTX.7.model6
ln -s C-H_vectors.m.1G6J C-H_vectors.m
ln -s C-H_medium1.m.1G6J C-H_medium1.m
ln -s N-H_vectors.m.1G6J N-H_vectors.m
ln -s N-H_medium1.m.1G6J N-H_medium1.m
