ln -s answerkey.m.1UD7 answerkey.m
ln -s myinput.m.1UD7 myinput.m
ln -s NOES.txt.1UD7 NOES.txt
ln -s order.m.1UD7 order.m
ln -s TOCSY.m.1UD7 TOCSY.m
ln -s MySHIFTS.7.model6.1UD7 SHIFTS/MySHIFTS.7.model6
ln -s MySHIFTX.7.model6.1UD7 SHIFTX/MySHIFTX.7.model6
ln -s C-H_vectors.m.1UD7 C-H_vectors.m
ln -s C-H_medium1.m.1UD7 C-H_medium1.m
ln -s N-H_vectors.m.1UD7 N-H_vectors.m
ln -s N-H_medium1.m.1UD7 N-H_medium1.m
