#ln -s answerkey.m.XinGao answerkey.m
ln -s myinput.m.XinGao myinput.m
ln -s NOES.txt.XinGao NOES.txt
ln -s order.m.XinGao order.m
#ln -s TOCSY.m.XinGao TOCSY.m
ln -s MySHIFTS.7.model6.XinGao SHIFTS/MySHIFTS.7.model6
ln -s MySHIFTX.7.model6.XinGao SHIFTX/MySHIFTX.7.model6
#ln -s N-H_vectors.m.XinGao N-H_vectors.m
#ln -s N-H_medium1.m.XinGao N-H_medium1.m
#ln -s N-C_vectors.m.XinGao N-C_vectors.m
#ln -s N-C_medium1.m.XinGao N-C_medium1.m
#ln -s C-Ca_vectors.m.XinGao C-Ca_vectors.m
#ln -s C-Ca_medium1.m.XinGao C-Ca_medium1.m
